name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 明确设置权限以允许创建发布版本
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -o go-app.exe
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: go-app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}